### ISSUE TITLE
[Moderation] Make sure content flags are correctly attributed

### ISSUE THREAD

**Issue by setch-l** [planetary-social/cleanstr#52] opened 2024-08-13 15:52 UTC
Overview

last week we saw multiple INPC posts flagged by the tagr-bot but when we went to look at the logs we could not find evidence of the bot tagging them or anyone else. Instead we found that they had flagged their own account back in May??? 

Our flagging labels should be clear for all use cases. 

Acceptance criteria:
- only posts that are flagged by the bot itself or go through our manual moderation system should be publicly flagged by Tagr-bot
- Self reported and publicly reported posts should follow the following labeling structure:
[Display name] has reported this note for [topic] 
[Display name has reported [Display name] account for [topic]

**Comment by mplorentz** [comment] 2024-09-24 18:52
From our meeting today: closing as a dupe of https://github.com/planetary-social/cleanstr/issues/53

**Closed as not planned by mplorentz** 2024-09-24 18:52 UTC
