### ISSUE TITLE
[Lists] Add the client marker to contact lists

### ISSUE THREAD

**Issue by setch-l** [planetary-social/cleanstr#51] opened 2024-08-13 15:47 UTC
Overview
For troubleshooting purposes it would be helpful to know on which client an update to the contact list occurred. This will help us measure whether Nos is overwriting contact lists or if it's some other app. [NIP-89](https://github.com/nostr-protocol/nips/blob/master/89.md#client-tag) has a spec for a "Client Tag" that we can use.

AC:
- Add the client marker to each content and account flag posted from Nos to say that it came from Nos.

**Comment by mplorentz** [comment] 2024-09-24 19:01
From our meeting today: closing as a dupe of https://github.com/planetary-social/nos/issues/1455 (even though the title was talking about moderation, this was supposed to be about contact lists)

**Comment by mplorentz** [comment] 2024-10-15 20:52
It occurred to me while implementing this that once we publish a contact list with the Nos tag, other Nostr apps may preserve that tag when they publish new versions of the list.

To mitigate this I added code to fire a new "Published Contact List" analytics event as well. Now if our server-side alert goes off we can check Posthog to verify whether the event that overwrote the contact list was actually published by Nos or not.

**Closed** 2024-11-13 14:53 UTC
